package main

import (
	"fmt"
	"os"
	"src/mapreduce"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// Split value into words, emit (word, document) pairs
	wordSet := make(map[string]struct{})
	word := ""
	for _, r := range value {
		if ('a' <= r && r <= 'z') || ('A' <= r && r <= 'Z') {
			word += string(r)
		} else if word != "" {
			wordSet[word] = struct{}{}
			word = ""
		}
	}
	if word != "" {
		wordSet[word] = struct{}{}
	}
	for w := range wordSet {
		res = append(res, mapreduce.KeyValue{w, document})
	}
	return
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// Remove duplicates, sort, and join document names
	docSet := make(map[string]struct{})
	for _, doc := range values {
		docSet[doc] = struct{}{}
	}
	docs := make([]string, 0, len(docSet))
	for doc := range docSet {
		docs = append(docs, doc)
	}
	// Sort for deterministic output
	for i := 0; i < len(docs); i++ {
		for j := i + 1; j < len(docs); j++ {
			if docs[j] < docs[i] {
				docs[i], docs[j] = docs[j], docs[i]
			}
		}
	}
	return fmt.Sprintf("%d %s", len(docs), join(docs, ","))
}

func join(arr []string, sep string) string {
	if len(arr) == 0 {
		return ""
	}
	res := arr[0]
	for _, s := range arr[1:] {
		res += sep + s
	}
	return res
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
